WIP
arquivei/pipeline-image pull request #11
Opened 2020-09-18 20:25 UTC by victorlacorte

Pessoal, a ideia é discutir como incluir neste projeto um script que disponibiliza assets num bucket acessível publicamente no GCP. Alguns dos desafios são de flexibilizar o script sendo que existem algumas "convenções" que não necessariamente façam sentido em todas as situações (e.g. location como `us-central1`, metadata de todos os arquivos como `"Cache-Control:no-cache, max-age=0, no-transform"`, etc).

2020-09-21 12:20 UTC, andrelugomes approved these changes

2020-09-21 17:53 UTC, bruno-delfino1995 commented
Acho que as preocupações de particularidades podem ser desconsideradas apenas por mudar o nome do script de `deploy-to-gcp` pra `deploy-gcp-site`. O objetivo dessa imagem é ajudar com os nossos processos, não servir apenas de "proxy" para as ferramentas do google. Caso tenhamos alguma outra forma de deploy para o GCP que possua particularidades quanto a atributos, permissões, localização, etc; criamos outro script baseando-se no `gcloud` e `gsutil`.

2020-09-21 17:55 UTC, bruno-delfino1995 requested changes
Transmitir as particularidades e propósito do script através do nome para não parecer apenas um proxy do gsutil/gcloud. Talvez uma mudança de `deploy-to-gcp` para `deploy-gcp-site`.

2020-09-21 19:26 UTC, victorlacorte commented
> Acho que as preocupações de particularidades podem ser desconsideradas apenas por mudar o nome do script de `deploy-to-gcp` pra `deploy-gcp-site`. O objetivo dessa imagem é ajudar com os nossos processos, não servir apenas de "proxy" para as ferramentas do google. Caso tenhamos alguma outra forma de deploy para o GCP que possua particularidades quanto a atributos, permissões, localização, etc; criamos outro script baseando-se no `gcloud` e `gsutil`.

Concordo que não deve servir de proxy! E quis dizer que, se houvessem alguns usos bem-definidos, poderíamos criar variações de deploy baseados neles, por exemplo.

2020-09-21 20:05 UTC, bruno-delfino1995 commented
@victorlacorte A necessidade no momento é deploy de site e está sendo atendida pelo seu script, a única coisa que não convem isso é o nome do mesmo. A contribuição é valida se desconsiderarmos isso e não precisamos esperar surgir outros padrões, podemos submeter como está e melhorar depois.

2020-09-21 20:19 UTC, victorlacorte commented
@bruno-delfino1995 concordo com vc, e também acho que devamos melhorar aos poucos. É que, da forma como o script está neste momento, ele não atenderia nem aos projetos que o utilizam de maneira duplicada (então não poderia utilizar o da imagem Docker gerada por aqui)

2020-09-22 12:44 UTC, bruno-delfino1995 commented
A forma padrão de deploy de sites no [GCS](https://cloud.google.com/storage/docs/hosting-static-website#gsutil_1) é pelo root do bucket, então acredito que podemos trocar essa ultima linha e posteriormente adequar os outros projetos para estarem em conformidade com esse processo.

2020-09-22 13:01 UTC, bruno-delfino1995 approved these changes

2020-09-22 13:01 UTC, merged